version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "markdown"
      - dependency-name: "usvg"
    groups:
      cli:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "monthly"
    groups:
      web-application:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/crates/cli"
    schedule:
      interval: "monthly"
    groups:
      docker:
        patterns:
          - "*"

