name: Build images

on:
  push:
    branches:
      - main

jobs:
  build-landscape2-image:
    if: github.ref == 'refs/heads/main'
    runs-on:
      labels: ubuntu-latest-8-cores
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -f crates/cli/Dockerfile \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.description=Landscape2 CLI tool" \
            --label "org.opencontainers.image.licenses=Apache-2.0" \
            -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest
