name: Build images

on:
  push:
    branches:
      - main

jobs:
  build-landscape2-image:
    if: github.ref == 'refs/heads/main'
    runs-on:
      labels: ubuntu-latest-8-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to AWS Public ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push image
        run: |
          docker build -f Dockerfile -t public.ecr.aws/g6m3a0y9/landscape2:latest .
          docker push public.ecr.aws/g6m3a0y9/landscape2:latest
